# Configuration for librarian-puppet. For example:
#
forge "http://forge.puppetlabs.com"

mod "puppetlabs/stdlib"
mod "puppetlabs/apt"
mod "stankevich/python"
mod 'mongodb', :git => 'https://github.com/puphpet/puppetlabs-mongodb.git'
mod "saz/timezone"
