# Configuration for librarian-puppet. For example:
#
forge "http://forge.puppetlabs.com"

mod "puppetlabs/stdlib"
mod "puppetlabs/apt"
mod "stankevich/python"
mod "puppetlabs/mysql"
mod "saz/timezone"
